export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';

export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_SINGLE_REQUEST = 'COURSE_SINGLE_REQUEST';
export const COURSE_SINGLE_SUCCESS = 'COURSE_SINGLE_SUCCESS';
export const COURSE_SINGLE_FAIL = 'COURSE_SINGLE_FAIL';

export const TEACHERS_LIST_REQUEST = 'TEACHERS_LIST_REQUEST';
export const TEACHERS_LIST_SUCCESS = 'TEACHERS_LIST_SUCCESS';
export const TEACHERS_LIST_FAIL = 'TEACHERS_LIST_FAIL';

export const TEACHERS_CREATE_REQUEST = 'TEACHERS_CREATE_REQUEST';
export const TEACHERS_CREATE_SUCCESS = 'TEACHERS_CREATE_SUCCESS';
export const TEACHERS_CREATE_FAIL = 'TEACHERS_CREATE_FAIL';

export const TEACHERS_UPDATE_REQUEST = 'TEACHERS_UPDATE_REQUEST';
export const TEACHERS_UPDATE_SUCCESS = 'TEACHERS_UPDATE_SUCCESS';
export const TEACHERS_UPDATE_FAIL = 'TEACHERS_UPDATE_FAIL';

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL';

export const COURSE_ARCHIVE_REQUEST = 'COURSE_ARCHIVE_REQUEST';
export const COURSE_ARCHIVE_SUCCESS = 'COURSE_ARCHIVE_SUCCESS';
export const COURSE_ARCHIVE_FAIL = 'COURSE_ARCHIVE_FAIL';

export const COURSE_EDIT_REQUEST = 'COURSE_EDIT_REQUEST';
export const COURSE_EDIT_SUCCESS = 'COURSE_EDIT_SUCCESS';
export const COURSE_EDIT_FAIL = 'COURSE_EDIT_FAIL';

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST';
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS';
export const COURSE_DELETE_FAIL = 'COURSE_DELETE_FAIL';

export const COURSE_STUDENTS_REQUEST = 'COURSE_STUDENTS_REQUEST';
export const COURSE_STUDENTS_SUCCESS = 'COURSE_STUDENTS_SUCCESS';
export const COURSE_STUDENTS_FAIL = 'COURSE_STUDENTS_FAIL';