export const ENROLL_REQUESTS_LIST_REQUEST = "ENROLL_REQUESTS_LIST_REQUEST";
export const ENROLL_REQUESTS_LIST_SUCCESS = "ENROLL_REQUESTS_LIST_SUCCESS";
export const ENROLL_REQUESTS_LIST_FAIL = "ENROLL_REQUESTS_LIST_FAIL";

export const ENROLL_REQUESTS_UPDATE_REQUEST = "ENROLL_REQUESTS_UPDATE_REQUEST";
export const ENROLL_REQUESTS_UPDATE_SUCCESS = "ENROLL_REQUESTS_UPDATE_SUCCESS";
export const ENROLL_REQUESTS_UPDATE_FAIL = "ENROLL_REQUESTS_UPDATE_FAIL";
