export const FACULTY_CREATE_REQUEST = 'FACULTY_CREATE_REQUEST';
export const FACULTY_CREATE_SUCCESS = 'FACULTY_CREATE_SUCCESS';
export const FACULTY_CREATE_FAIL = 'FACULTY_CREATE_FAIL';

export const FACULTY_UPDATE_REQUEST = 'FACULTY_UPDATE_REQUEST';
export const FACULTY_UPDATE_SUCCESS = 'FACULTY_UPDATE_SUCCESS';
export const FACULTY_UPDATE_FAIL = 'FACULTY_UPDATE_FAIL';

export const FACULTY_TYPES_REQUEST = 'FACULTY_TYPES_REQUEST';
export const FACULTY_TYPES_SUCCESS = 'FACULTY_TYPES_SUCCESS';
export const FACULTY_TYPES_FAIL = 'FACULTY_TYPES_FAIL';

export const FACULTY_DELETE_REQUEST = 'FACULTY_DELETE_REQUEST';
export const FACULTY_DELETE_SUCCESS = 'FACULTY_DELETE_SUCCESS';
export const FACULTY_DELETE_FAIL = 'FACULTY_DELETE_FAIL';
