export const HISTORY_LIST_REQUEST = "HISTORY_LIST_REQUEST";
export const HISTORY_LIST_SUCCESS = "HISTORY_LIST_SUCCESS";
export const HISTORY_LIST_FAIL = "HISTORY_LIST_FAIL";

export const HISTORY_USER_REQUEST = "HISTORY_USER_REQUEST";
export const HISTORY_USER_SUCCESS = "HISTORY_USER_SUCCESS";
export const HISTORY_USER_FAIL = "HISTORY_USER_FAIL";

export const UPDATE_BALANCE_REQUEST = "UPDATE_BALANCE_REQUEST";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAIL = "UPDATE_BALANCE_FAIL";

export const HISTORY_USER_LIST_REQUEST = "HISTORY_USER_LIST_REQUEST";
export const HISTORY_USER_LIST_SUCCESS = "HISTORY_USER_LIST_SUCCESS";
export const HISTORY_USER_LIST_FAIL = "HISTORY_USER_LIST_FAIL";

export const RESET_USER_DEVICE_REQUEST = "RESET_USER_DEVICE_REQUEST";
export const RESET_USER_DEVICE_SUCCESS = "RESET_USER_DEVICE_SUCCESS";
export const RESET_USER_DEVICE_FAIL = "RESET_USER_DEVICE_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_PASSWORD_REQUEST = "USER_UPDATE_PASSWORD_REQUEST";
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";

export const UPDATE_MULTI_BALANCE_REQUEST = "UPDATE_MULTI_BALANCE_REQUEST";
export const UPDATE_MULTI_BALANCE_SUCCESS = "UPDATE_MULTI_BALANCE_SUCCESS";
export const UPDATE_MULTI_BALANCE_FAIL = "UPDATE_MULTI_BALANCE_FAIL";
