export const LESSON_CREATE_REQUEST = 'LESSON_CREATE_REQUEST';
export const LESSON_CREATE_SUCCESS = 'LESSON_CREATE_SUCCESS';
export const LESSON_CREATE_FAIL = 'LESSON_CREATE_FAIL';

export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST';
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS';
export const LESSON_LIST_FAIL = 'LESSON_LIST_FAIL';

export const LESSON_SINGLE_REQUEST = 'LESSON_SINGLE_REQUEST';
export const LESSON_SINGLE_SUCCESS = 'LESSON_SINGLE_SUCCESS';
export const LESSON_SINGLE_FAIL = 'LESSON_SINGLE_FAIL';

export const LESSON_UPDATE_REQUEST = 'LESSON_UPDATE_REQUEST';
export const LESSON_UPDATE_SUCCESS = 'LESSON_UPDATE_SUCCESS';
export const LESSON_UPDATE_FAIL = 'LESSON_UPDATE_FAIL';

export const LESSON_EDIT_REQUEST = 'LESSON_EDIT_REQUEST';
export const LESSON_EDIT_SUCCESS = 'LESSON_EDIT_SUCCESS';
export const LESSON_EDIT_FAIL = 'LESSON_EDIT_FAIL';

export const LESSON_STUDENTS_REQUEST = 'LESSON_STUDENTS_REQUEST';
export const LESSON_STUDENTS_SUCCESS = 'LESSON_STUDENTS_SUCCESS';
export const LESSON_STUDENTS_FAIL = 'LESSON_STUDENTS_FAIL';