export const UNIVERSITY_CREATE_REQUEST = 'UNIVERSITY_CREATE_REQUEST';
export const UNIVERSITY_CREATE_SUCCESS = 'UNIVERSITY_CREATE_SUCCESS';
export const UNIVERSITY_CREATE_FAIL = 'UNIVERSITY_CREATE_FAIL';

export const UNIVERSITY_LIST_REQUEST = 'UNIVERSITY_LIST_REQUEST';
export const UNIVERSITY_LIST_SUCCESS = 'UNIVERSITY_LIST_SUCCESS';
export const UNIVERSITY_LIST_FAIL = 'UNIVERSITY_LIST_FAIL';

export const UNIVERSITY_FACULTIES_LIST_REQUEST = 'UNIVERSITY_FACULTIES_LIST_REQUEST';
export const UNIVERSITY_FACULTIES_LIST_SUCCESS = 'UNIVERSITY_FACULTIES_LIST_SUCCESS';
export const UNIVERSITY_FACULTIES_LIST_FAIL = 'UNIVERSITY_FACULTIES_LIST_FAIL';

export const UNIVERSITY_UPDATE_REQUEST = 'UNIVERSITY_UPDATE_REQUEST';
export const UNIVERSITY_UPDATE_SUCCESS = 'UNIVERSITY_UPDATE_SUCCESS';
export const UNIVERSITY_UPDATE_FAIL = 'UNIVERSITY_UPDATE_FAIL';

export const UNIVERSITY_DELETE_REQUEST = 'UNIVERSITY_DELETE_REQUEST';
export const UNIVERSITY_DELETE_SUCCESS = 'UNIVERSITY_DELETE_SUCCESS';
export const UNIVERSITY_DELETE_FAIL = 'UNIVERSITY_DELETE_FAIL';